# configs/nfsba_cifar10.yaml (Using CNN Generator + Feature Consistency + Freq Smoothness)

# General Config
seed: 42
dataset: CIFAR10
num_classes: 10
img_size: 32
device: cuda

# Data Config
data_path: ./data/datasets
batch_size: 512 # 保持不变，可以根据GPU内存调整
num_workers: 8

# Proxy Model Training Specific Config (如果需要重新训练代理模型)
proxy_training:
  epochs: 50
  lr: 0.001
  weight_decay: 0.01

# Attack Config
attack: NFSBA
poison_rate: 0.05
target_label: 0
dct_block_size: 8
condition_type: embedding
condition_dim: 16

# Generator Config
generator:
  type: "CNN" # 保持 CNNGenerator
  lr: 0.0005
  betas: [0.5, 0.999]
  epochs: 50
  checkpoint_path: ./checkpoints/generator_cifar10_cnn_featcons_freqsmooth.pt # <-- 新路径
  # === 新损失权重 ===
  lambda_stat_dist: [0.5, 1.0]           # 保持统计损失
  lambda_stat_energy: [0.5, 1.0]          # 保持统计损失
  lambda_feature_consistency: [1.0, 0.5]  # 新增: 特征一致性损失 (初期权重高)
  lambda_smooth_freq: [0.1, 0.5]        # 新增: 频域平滑度损失 (初期权重低)
  lambda_perturb: [0.5, 1.0]            # 保留: 总扰动损失 (权重可调整或设为0)
  # 移除了 lambda_trigger 和 lambda_lpips
  # ==================
  phase1_epochs_ratio: 0.8
  resume_generator: False
  initial_scale: 0.1 # 扰动输出的初始缩放因子
  learnable_scale: False

# --- 新增: 特征一致性损失配置 ---
feature_consistency:
  proxy_idx: 0 # 使用哪个代理模型计算特征 (索引从0开始)
  feature_layer_name: 'avgpool' # 用于提取特征的代理模型层名 (需要确认对ShallowResNet有效)
  center_num_samples: 1024 # 用于计算目标类特征中心的干净样本数量
  loss_type: 'l2' # 'l2' 或 'cosine'
# --------------------------------

# Proxy Model Config (Ensemble)
proxy_models:
  names: ['ShallowResNet'] # 可以添加更多代理模型
  paths:
    - ./checkpoints/proxy_shallowresnet_cifar10.pt # 确保代理模型已训练

# Quantization Simulation Config
quantization:
  simulate: False # 保持禁用，可以在之后启用
  qf: 75

# Statistics Config
stats:
  target_path: ./stats/cifar10_clean_dct_stats.pt # 确保统计数据已生成

# Victim Model Config (训练受害者模型时使用)
victim_model:
  name: ResNet18
  pretrained: True
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0005
  epochs: 50
  checkpoint_path: ./checkpoints/victim_resnet18_nfsba_cifar10_cnn_featcons_freqsmooth.pt

# Efficiency Config
use_amp: True

# DDP Config
master_port: '12355'