# configs/nfsba_cifar10.yaml (Using CNN Generator + LPIPS)

# General Config
seed: 42
dataset: CIFAR10
num_classes: 10
img_size: 32
device: cuda

# Data Config
data_path: ./data/datasets
batch_size: 512
num_workers: 8

# Proxy Model Training Specific Config
proxy_training:
  epochs: 50
  lr: 0.001
  weight_decay: 0.01

# Attack Config
attack: NFSBA
poison_rate: 0.01
target_label: 0
dct_block_size: 8
condition_type: embedding
condition_dim: 16

# Generator Config
generator:
  type: "CNN" # <-- 使用新的 CNNGenerator
  # hidden_dims 不再需要，CNN 结构是固定的
  lr: 0.0005 # CNN 可能需要稍低的学习率
  betas: [0.5, 0.999]
  epochs: 50
  checkpoint_path: ./checkpoints/generator_cifar10_cnn_lpips.pt # <-- 新路径
  # === 损失权重 ===
  lambda_stat_dist: [1.0, 1.0]   # 保持统计损失
  lambda_stat_energy: [1.0, 1.0] # 保持统计损失
  lambda_trigger: [0.0001, 0.0001]     # 保持触发器权重
  lambda_perturb: [1.0, 10.0]     # Lpert 设为 0，依靠 LPIPS
  lambda_lpips: [2.0, 10.0]       # 启用 LPIPS 损失
  # ==================
  phase1_epochs_ratio: 0.4
  resume_generator: False
  # --- 控制 Tanh 后的缩放因子 ---
  initial_scale: 0.1 # 保持 0.2
  learnable_scale: False # 保持 False


# Proxy Model Config (Ensemble)
proxy_models:
  names: ['ShallowResNet']
  paths:
    - ./checkpoints/proxy_shallowresnet_cifar10.pt

# Quantization Simulation Config
quantization:
  simulate: False # 保持禁用以调试
  qf: 75

# Statistics Config
stats:
  target_path: ./stats/cifar10_clean_dct_stats.pt

# Victim Model Config (Not relevant now)
victim_model:
  name: ResNet18
  pretrained: True
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0005
  epochs: 50
  checkpoint_path: ./checkpoints/victim_resnet18_nfsba_cifar10_cnn_lpips.pt

# Efficiency Config
use_amp: True

# DDP Config
master_port: '12355'